services:
  db:
    image: postgres:18
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: swopcart
      POSTGRES_USER: swopcart
      POSTGRES_PASSWORD: swopcart
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
